version: '3'

# Define services
services:

  # App Service
  app:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on: 
      - redis
    environment:
      REDIS_URL: redis:6379 # That's how it works in a defined network!
      APP_PORT: 8080
      APP_URL: app
    networks: # Networks to join
      - backend

  # Canary Service
  canary:
    build:
      context: canary
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - redis # This should not be the case! But taking a shortcut to implement this canary
    environment:
      REDIS_URL: redis:6379
    networks:
      - backend


  # Redis Service
  redis:
    image: "redis:alpine" # a non persistent one!
    ports: 
      - "6379:6379"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:    